### PR TITLE
Bump version to 0.8.0

### PR DESCRIPTION
**Pull request by ekoval**
#35

### CODE REVIEW

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by blaix** [comment]
should new optional params bump patch instead of minor on a 0.x version?

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by stormf** [comment]
The wrong version got tagged and uploaded by jenkins cloberring the `0.7.1` build.

I've checked out `0.7.1` and reuploaded it. Then I fixed the `0.7.2` tag to point to this commit (which confusing says `Bump version to 0.8.0` in the description) and uploaded that one to yolapi.

This is a public repo, but we're not uploading to pypi, I assume that's intentional?

**Comment by blaix** [comment]
> This is a public repo, but we're not uploading to pypi, I assume that's intentional?

I'm not sure why we wouldn't. @ekoval? @RayeN?

**Comment by ekoval** [comment]
Have no idea :(

**Comment by RayeN** [comment]
> I'm not sure why we wouldn't. @ekoval? @RayeN?

I don't see any reason why we shouldn't do that.  I think we didn't do that initially since it depended on `yoconfigurator`/`yoconfig` which were not public at that time (but I might be wrong about that).

@stormf, @stefanor I think we can start uploading it to pypi as well unless you have some objections.

**Comment by stefanor** [comment]
I would suggest asking sitewit how they feel about us publishing it. It is their name.

**Pull request merged**
